/**
* Author: mgarciareimers
* Date: 02/02/2021
* 
* Description: Number constants.
*/
module.exports = {
    DEFAULT_GET_AUTHORS_LIMIT: 25,
    DEFAULT_GET_BOOKS_LIMIT: 25,
    DEFAULT_GET_CATEGORIES_LIMIT: 25,
    DEFAULT_GET_USERS_LIMIT: 25,
    GET_DOCUMENT_FIRST_PAGE: 1,
    HASH_SALT_OR_ROUNDS: 10,
    PASSWORD_MIN_LENGTH: 8,
    RANDOM_PASSWORD_LENGTH: 16,
    RANDOM_VERIFICATION_TOKEN_LENGTH: 16,
}